"""
Task 1 bonus - one-page equity research brief.

Produces a self-contained HTML document (and optionally Markdown/PDF) combining
the Task 1A pipeline output with the Task 1B LLM analysis.

SELF-CONTAINED IS THE POINT
---------------------------
The chart is embedded as a base64 data URI and all CSS is inline. The output is
a single .html file that renders identically from a repository, an email
attachment, or a Drive link with no external requests. A brief that only renders
next to its own /images folder is not a deliverable.

Required content, per the brief: company snapshot, technical outlook, news
sentiment summary with the top three headlines, the LLM recommendation with its
reasoning, and a mandatory risk disclaimer. The disclaimer is rendered by the
template rather than passed in, so it cannot be accidentally omitted.

# AI-ASSISTED: Claude (claude-sonnet-5), Prompt: 'Build a self-contained HTML
# equity research brief with an embedded base64 matplotlib chart and a
# mandatory risk disclaimer', Date: 2026-09-10
"""

from __future__ import annotations

import base64
import io
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Sequence

import matplotlib
matplotlib.use("Agg")          # Headless backend - required on Colab and in CI.
import matplotlib.dates as mdates            # noqa: E402
import matplotlib.pyplot as plt              # noqa: E402
import pandas as pd                          # noqa: E402
from jinja2 import Environment, select_autoescape   # noqa: E402

logger = logging.getLogger(__name__)

CHART_SESSIONS = 252          # One trading year - enough context without crowding.
RECOMMENDATION_COLOURS = {"Buy": "#0f7b4f", "Hold": "#8a6d1f", "Sell": "#a32b2b"}

RISK_DISCLAIMER = (
    "This document is generated by an automated research pipeline for technical "
    "demonstration purposes only. It is not investment advice, not a recommendation "
    "to buy or sell any security, and has not been reviewed by a licensed financial "
    "adviser. Signals are produced by a large language model reasoning over "
    "mechanically computed indicators, and large language models can and do produce "
    "confident, incorrect output. Past performance does not indicate future results. "
    "Conduct your own research and consult a qualified professional before making "
    "any investment decision."
)


# ---------------------------------------------------------------------------
# Chart
# ---------------------------------------------------------------------------
def build_price_chart(enriched: pd.DataFrame, ticker: str, sessions: int = CHART_SESSIONS) -> str:
    """Render price/MA/Bollinger plus RSI and MACD panels; return a data URI.

    Three stacked panels sharing an x-axis, height-weighted 3:1:1 so the price
    action dominates. Reference lines at RSI 30/70 and MACD zero are what make
    the panels readable at a glance without a legend lookup.
    """
    window = enriched.iloc[-sessions:] if len(enriched) > sessions else enriched
    if window.empty:
        raise ValueError("Cannot chart an empty frame.")

    figure, (price_ax, rsi_ax, macd_ax) = plt.subplots(
        3, 1, figsize=(10, 8), sharex=True,
        gridspec_kw={"height_ratios": [3, 1, 1], "hspace": 0.08},
    )
    figure.patch.set_facecolor("white")

    # --- Panel 1: price, moving averages, Bollinger channel ---
    if {"bb_upper", "bb_lower"}.issubset(window.columns):
        price_ax.fill_between(
            window.index, window["bb_lower"], window["bb_upper"],
            color="#4a6fa5", alpha=0.10, label="Bollinger (20, 2)", zorder=1,
        )
    price_ax.plot(window.index, window["Close"], color="#1b2a41", linewidth=1.5, label="Close", zorder=4)
    for column, colour, label in (
        ("sma_50", "#d98324", "SMA-50"),
        ("sma_200", "#7b2d8e", "SMA-200"),
    ):
        if column in window.columns and window[column].notna().any():
            price_ax.plot(window.index, window[column], color=colour, linewidth=1.2,
                          label=label, alpha=0.9, zorder=3)

    price_ax.set_ylabel("Price", fontsize=9)
    price_ax.set_title(f"{ticker} - 12-month technical overview", fontsize=12,
                       fontweight="bold", loc="left", pad=10)
    price_ax.legend(loc="upper left", fontsize=8, framealpha=0.9, ncol=4)
    price_ax.grid(alpha=0.25, linewidth=0.6)

    # --- Panel 2: RSI with the conventional 30/70 bands ---
    if "rsi_14" in window.columns:
        rsi_ax.plot(window.index, window["rsi_14"], color="#2a6f97", linewidth=1.2)
        rsi_ax.axhline(70, color="#a32b2b", linestyle="--", linewidth=0.8, alpha=0.7)
        rsi_ax.axhline(30, color="#0f7b4f", linestyle="--", linewidth=0.8, alpha=0.7)
        rsi_ax.axhspan(30, 70, color="#cccccc", alpha=0.12)
        rsi_ax.set_ylim(0, 100)
        rsi_ax.set_yticks([0, 30, 50, 70, 100])
    rsi_ax.set_ylabel("RSI-14", fontsize=9)
    rsi_ax.grid(alpha=0.25, linewidth=0.6)

    # --- Panel 3: MACD with a signed histogram ---
    if {"macd", "macd_signal", "macd_hist"}.issubset(window.columns):
        macd_ax.plot(window.index, window["macd"], color="#1b2a41", linewidth=1.1, label="MACD")
        macd_ax.plot(window.index, window["macd_signal"], color="#d98324", linewidth=1.1, label="Signal")
        histogram = window["macd_hist"]
        macd_ax.bar(
            window.index, histogram, width=1.0, alpha=0.45,
            color=["#0f7b4f" if v >= 0 else "#a32b2b" for v in histogram.fillna(0)],
        )
        macd_ax.axhline(0, color="#555555", linewidth=0.8)
        macd_ax.legend(loc="upper left", fontsize=8, framealpha=0.9, ncol=2)
    macd_ax.set_ylabel("MACD", fontsize=9)
    macd_ax.grid(alpha=0.25, linewidth=0.6)

    macd_ax.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
    macd_ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
    figure.autofmt_xdate(rotation=0, ha="center")

    for axis in (price_ax, rsi_ax, macd_ax):
        for spine in ("top", "right"):
            axis.spines[spine].set_visible(False)

    buffer = io.BytesIO()
    figure.savefig(buffer, format="png", dpi=130, bbox_inches="tight", facecolor="white")
    plt.close(figure)
    encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
    return f"data:image/png;base64,{encoded}"


# ---------------------------------------------------------------------------
# Template
# ---------------------------------------------------------------------------
_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ s.ticker }} - Equity Research Brief</title>
<style>
  :root { --ink:#1b2a41; --muted:#5b6b7f; --line:#dfe4ea; --bg:#f7f8fa; --accent:{{ rec_colour }}; }
  * { box-sizing:border-box; }
  body { margin:0; padding:24px 16px; background:var(--bg); color:var(--ink);
         font:14px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; }
  .sheet { max-width:900px; margin:0 auto; background:#fff; border:1px solid var(--line);
           border-radius:10px; padding:28px 30px; }
  header { border-bottom:3px solid var(--accent); padding-bottom:14px; margin-bottom:20px; }
  h1 { margin:0 0 4px; font-size:23px; letter-spacing:-.2px; }
  .sub { color:var(--muted); font-size:12.5px; }
  h2 { font-size:12px; text-transform:uppercase; letter-spacing:.9px; color:var(--muted);
       margin:26px 0 10px; padding-bottom:5px; border-bottom:1px solid var(--line); }
  .rec { display:inline-block; background:var(--accent); color:#fff; padding:5px 16px;
         border-radius:5px; font-weight:700; font-size:15px; letter-spacing:.4px; }
  .conf { color:var(--muted); font-size:12.5px; margin-left:9px; }
  .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(140px,1fr)); gap:10px; }
  .cell { background:var(--bg); border:1px solid var(--line); border-radius:7px; padding:9px 11px; }
  .cell .k { font-size:10.5px; text-transform:uppercase; letter-spacing:.5px; color:var(--muted); }
  .cell .v { font-size:16px; font-weight:600; margin-top:3px; }
  .pos { color:#0f7b4f; } .neg { color:#a32b2b; } .na { color:var(--muted); font-weight:400; font-size:14px; }
  img { width:100%; height:auto; border:1px solid var(--line); border-radius:7px; }
  table { width:100%; border-collapse:collapse; font-size:13px; }
  th,td { text-align:left; padding:7px 9px; border-bottom:1px solid var(--line); vertical-align:top; }
  th { font-size:10.5px; text-transform:uppercase; letter-spacing:.5px; color:var(--muted); }
  .pill { display:inline-block; padding:1px 8px; border-radius:20px; font-size:11px; font-weight:600; }
  .pill.positive { background:#e3f2ea; color:#0f7b4f; }
  .pill.negative { background:#fbe9e9; color:#a32b2b; }
  .pill.neutral  { background:#eceff3; color:#5b6b7f; }
  ul { margin:6px 0; padding-left:19px; } li { margin:3px 0; }
  .just { background:var(--bg); border-left:3px solid var(--accent); padding:12px 15px;
          border-radius:0 7px 7px 0; margin:10px 0 16px; }
  .warn { background:#fff7e6; border:1px solid #ffd88a; border-radius:7px;
          padding:9px 12px; font-size:12.5px; margin:12px 0; }
  .disc { margin-top:26px; padding:13px 15px; background:#fbfbfc; border:1px solid var(--line);
          border-radius:7px; font-size:11px; line-height:1.5; color:var(--muted); }
  .disc strong { color:#a32b2b; display:block; margin-bottom:4px; font-size:11.5px;
                 text-transform:uppercase; letter-spacing:.6px; }
  footer { margin-top:16px; font-size:10.5px; color:var(--muted); text-align:center; }
  @media print { body { background:#fff; padding:0; } .sheet { border:0; } }
</style></head><body><div class="sheet">

<header>
  <h1>{{ s.company_name }} <span style="color:var(--muted);font-weight:400">({{ s.ticker }})</span></h1>
  <div class="sub">
    {{ s.sector or "Sector n/a" }}{% if s.industry %} &middot; {{ s.industry }}{% endif %}
    &middot; Data as at {{ s.as_of }} &middot; {{ s.sessions_analysed }} sessions analysed
  </div>
</header>

{% if signal %}
<h2>Recommendation</h2>
<div>
  <span class="rec">{{ signal.recommendation.value }}</span>
  <span class="conf">Model confidence {{ "%.0f"|format(signal.confidence * 100) }}%</span>
</div>
{% if is_fallback %}
<div class="warn"><strong>Degraded output.</strong> The language model did not produce a
justification that passed validation. This signal was generated by the deterministic
rules-based fallback and carries no qualitative judgement.</div>
{% endif %}
<div class="just">{{ signal.justification }}</div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:22px">
  <div><strong style="font-size:12.5px">Key drivers</strong>
    <ul>{% for d in signal.key_drivers %}<li>{{ d }}</li>{% endfor %}</ul></div>
  <div><strong style="font-size:12.5px">Risks to this view</strong>
    <ul>{% for r in signal.risks %}<li>{{ r }}</li>{% endfor %}</ul></div>
</div>
{% endif %}

<h2>Company snapshot</h2>
<div class="grid">
  {% for label, value, cls in snapshot_cells %}
  <div class="cell"><div class="k">{{ label }}</div>
    <div class="v {{ cls }}">{{ value }}</div></div>
  {% endfor %}
</div>

<h2>Technical outlook</h2>
<img src="{{ chart_uri }}" alt="{{ s.ticker }} price, RSI and MACD chart">
<div class="grid" style="margin-top:11px">
  {% for label, value, cls in technical_cells %}
  <div class="cell"><div class="k">{{ label }}</div>
    <div class="v {{ cls }}">{{ value }}</div></div>
  {% endfor %}
</div>
<ul style="margin-top:11px;font-size:13px">
  {% for line in s.momentum_rationale %}<li>{{ line }}</li>{% endfor %}
</ul>

<h2>News sentiment{% if aggregate %} &middot; {{ aggregate.headline_count }} headlines{% endif %}</h2>
{% if aggregate %}
<div class="grid" style="margin-bottom:12px">
  <div class="cell"><div class="k">Aggregate</div>
    <div class="v {{ 'pos' if aggregate.score > 0 else 'neg' if aggregate.score < 0 else '' }}">
      {{ aggregate.label.value|capitalize }} ({{ "%+.2f"|format(aggregate.score) }})</div></div>
  <div class="cell"><div class="k">Positive</div><div class="v pos">{{ aggregate.positive_count }}</div></div>
  <div class="cell"><div class="k">Neutral</div><div class="v">{{ aggregate.neutral_count }}</div></div>
  <div class="cell"><div class="k">Negative</div><div class="v neg">{{ aggregate.negative_count }}</div></div>
  <div class="cell"><div class="k">Mean confidence</div><div class="v">{{ "%.2f"|format(aggregate.mean_confidence) }}</div></div>
</div>
{% if aggregate.degenerate_warning %}
<div class="warn"><strong>Low-diversity warning.</strong> Every headline received the same
label and the same confidence, which usually indicates the classifier rubber-stamped the
batch rather than reading it. Treat the aggregate with caution.</div>
{% endif %}
<table><thead><tr><th style="width:70px">Sentiment</th><th style="width:52px">Conf.</th>
<th>Headline</th><th style="width:33%">Why</th></tr></thead><tbody>
{% for h in top_headlines %}
<tr><td><span class="pill {{ h.sentiment.value }}">{{ h.sentiment.value }}</span></td>
    <td>{{ "%.2f"|format(h.confidence) }}</td>
    <td>{{ h.headline }}</td><td style="color:var(--muted)">{{ h.brief_reason }}</td></tr>
{% endfor %}
</tbody></table>
{% else %}<p style="color:var(--muted)">No headline sentiment available for this run.</p>{% endif %}

{% if warnings %}
<h2>Pipeline warnings</h2>
<ul style="font-size:12.5px;color:var(--muted)">
  {% for w in warnings %}<li>{{ w }}</li>{% endfor %}</ul>
{% endif %}

<div class="disc"><strong>Risk disclaimer</strong>{{ disclaimer }}</div>
<footer>
  Generated {{ generated_at }} &middot; model {{ model_label }} &middot;
  prompts {{ prompt_label }} &middot; CDAZZDEV Senior MLE assessment, Task 1
</footer>
</div></body></html>"""


def _format_currency(value: Any, currency: str = "USD") -> str:
    if value is None:
        return "n/a"
    symbol = {"USD": "$", "GBP": "£", "EUR": "€", "LKR": "Rs "}.get(currency, "")
    return f"{symbol}{value:,.2f}"


def _format_signed_pct(value: Any) -> tuple[str, str]:
    if value is None:
        return "n/a", "na"
    return f"{value:+.2f}%", ("pos" if value > 0 else "neg" if value < 0 else "")


def render_html_brief(
    equity: Any,
    analysis: Any,
    output_path: str | Path = "output/equity_brief.html",
) -> Path:
    """Render the complete brief to a single self-contained HTML file."""
    summary = equity.summary
    currency = summary.get("currency", "USD")

    ytd_text, ytd_class = _format_signed_pct(summary.get("ytd_return_pct"))
    below_high_text, _ = _format_signed_pct(summary.get("pct_below_52w_high"))

    snapshot_cells = [
        ("Current price", _format_currency(summary.get("current_price"), currency), ""),
        ("52-week high", _format_currency(summary.get("fifty_two_week_high"), currency), ""),
        ("52-week low", _format_currency(summary.get("fifty_two_week_low"), currency), ""),
        ("From 52w high", below_high_text, ""),
        ("YTD return", ytd_text, ytd_class),
        ("P/E ratio",
         f"{summary['pe_ratio']:.2f}" if summary.get("pe_ratio") else "n/a",
         "" if summary.get("pe_ratio") else "na"),
    ]

    rsi = summary.get("rsi_14")
    rsi_class = "neg" if rsi and rsi >= 70 else "pos" if rsi and rsi <= 30 else ""
    histogram = summary.get("macd_histogram")

    technical_cells = [
        ("SMA-50", _format_currency(summary.get("sma_50"), currency), ""),
        ("SMA-200", _format_currency(summary.get("sma_200"), currency), ""),
        ("RSI-14", f"{rsi:.1f}" if rsi is not None else "n/a", rsi_class),
        ("MACD histogram",
         f"{histogram:+.3f}" if histogram is not None else "n/a",
         "pos" if histogram and histogram > 0 else "neg" if histogram else ""),
        ("Bollinger %B",
         f"{summary['bollinger_pct_b']:.2f}" if summary.get("bollinger_pct_b") is not None else "n/a", ""),
        ("Momentum screen",
         str(summary.get("momentum_signal", "n/a")).replace("_", " ").title(),
         "pos" if (summary.get("momentum_score") or 0) > 0 else "neg" if (summary.get("momentum_score") or 0) < 0 else ""),
        ("Annualised vol (30d)",
         f"{summary['annualised_volatility_30d'] * 100:.1f}%"
         if summary.get("annualised_volatility_30d") is not None else "n/a", ""),
    ]

    top_headlines: Sequence[Any] = sorted(
        analysis.headline_sentiments, key=lambda h: h.confidence, reverse=True
    )[:3]

    models = analysis.model_manifest.get("providers", []) if analysis.model_manifest else []
    model_label = f"{models[0]['provider']}/{models[0]['model']}" if models else "n/a"
    prompt_label = ", ".join(f"{p['name']} {p['version']}" for p in analysis.prompt_versions) or "n/a"

    environment = Environment(autoescape=select_autoescape(["html"]))
    html = environment.from_string(_TEMPLATE).render(
        s=summary,
        signal=analysis.signal,
        is_fallback=analysis.signal_is_fallback,
        aggregate=analysis.aggregate,
        top_headlines=top_headlines,
        snapshot_cells=snapshot_cells,
        technical_cells=technical_cells,
        chart_uri=build_price_chart(equity.prices, equity.ticker),
        warnings=equity.warnings,
        disclaimer=RISK_DISCLAIMER,
        rec_colour=RECOMMENDATION_COLOURS.get(
            analysis.signal.recommendation.value if analysis.signal else "Hold", "#5b6b7f"
        ),
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        model_label=model_label,
        prompt_label=prompt_label,
    )

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(html, encoding="utf-8")
    logger.info("Brief written to %s (%.1f KB).", destination, destination.stat().st_size / 1024)
    return destination


def render_markdown_brief(
    equity: Any, analysis: Any, output_path: str | Path = "output/equity_brief.md"
) -> Path:
    """Markdown variant. The brief allows Markdown; HTML is the richer artefact,
    but Markdown renders natively on GitHub, so both are produced."""
    summary, signal, aggregate = equity.summary, analysis.signal, analysis.aggregate
    lines = [
        f"# {summary.get('company_name')} ({summary.get('ticker')}) - Equity Research Brief",
        "",
        f"*Data as at {summary.get('as_of')} · {summary.get('sessions_analysed')} sessions analysed*",
        "",
        "## Recommendation",
        "",
    ]
    if signal:
        lines += [
            f"**{signal.recommendation.value}** — model confidence {signal.confidence:.0%}"
            + ("  \n> ⚠️ Rules-based fallback: LLM output failed validation." if analysis.signal_is_fallback else ""),
            "", f"> {signal.justification}", "",
            "**Key drivers**", "", *[f"- {d}" for d in signal.key_drivers], "",
            "**Risks to this view**", "", *[f"- {r}" for r in signal.risks], "",
        ]

    lines += [
        "## Company snapshot", "",
        "| Metric | Value |", "|---|---|",
        f"| Current price | {_format_currency(summary.get('current_price'), summary.get('currency','USD'))} |",
        f"| 52-week high | {_format_currency(summary.get('fifty_two_week_high'), summary.get('currency','USD'))} |",
        f"| 52-week low | {_format_currency(summary.get('fifty_two_week_low'), summary.get('currency','USD'))} |",
        f"| YTD return | {_format_signed_pct(summary.get('ytd_return_pct'))[0]} |",
        f"| P/E ratio | {summary.get('pe_ratio') or 'n/a'} |",
        "", "## Technical outlook", "",
        "| Indicator | Value |", "|---|---|",
        f"| SMA-50 | {summary.get('sma_50') or 'n/a'} |",
        f"| SMA-200 | {summary.get('sma_200') or 'n/a'} |",
        f"| RSI-14 | {summary.get('rsi_14') or 'n/a'} |",
        f"| MACD histogram | {summary.get('macd_histogram') or 'n/a'} |",
        f"| Bollinger %B | {summary.get('bollinger_pct_b') or 'n/a'} |",
        f"| Momentum screen | {summary.get('momentum_signal')} ({summary.get('momentum_score')}) |",
        "",
        *[f"- {line}" for line in summary.get("momentum_rationale", [])],
        "", "## News sentiment", "",
    ]
    if aggregate:
        lines += [
            f"Aggregate **{aggregate.label.value}** ({aggregate.score:+.2f}) across "
            f"{aggregate.headline_count} headlines — {aggregate.positive_count} positive, "
            f"{aggregate.neutral_count} neutral, {aggregate.negative_count} negative.", "",
            "| Sentiment | Confidence | Headline |", "|---|---|---|",
        ]
        for item in sorted(analysis.headline_sentiments, key=lambda h: h.confidence, reverse=True)[:3]:
            safe = item.headline.replace("|", "\\|")
            lines.append(f"| {item.sentiment.value} | {item.confidence:.2f} | {safe} |")
    else:
        lines.append("*No headline sentiment available.*")

    lines += ["", "---", "", f"> **RISK DISCLAIMER** — {RISK_DISCLAIMER}", ""]

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines), encoding="utf-8")
    return destination
